# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Course2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  
  
  # Pods for Course2
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'RealmSwift' 
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
end
